### ISSUE TITLE
Items search result page

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#10]
Naeem kent aan een item dat uit een online database komt een eigen type toe (item type 'europeana', (britishlibrary'...). Al die items moet eigenlijk in de item result page verschijnen, maar als ik een query probeer items van deze verschillende types op te halen, krijg ik 0 resultaten. Misschien werkt een OR niet of ben ik gewoon fout in mijn query?/aezel-erfgoed/solr-search?q=&facet=itemtype:%22Object%22+OR+itemtype:%22Europeana%22

Een ander probleem is dat de query dan direct heel lang gaat worden want er zijn nogal wat online databases doorzoekbaar. Ik denk dat het beter is dat we alle online content het itemtype 'Object' toekennen en dat de herkomst (e.g. Europeana) eventueel aan het veld source wordt toegevoegd.

![image](https://user-images.githubusercontent.com/3798589/28531299-c0d6dbe2-7096-11e7-8b02-b5f982178622.png)

**Comment by roxannewyns** [comment]
Nog eens gecheckt, en contributed items krijgen idd automatisch als item type 'contributed'. Hoe gaan we dat oplossen met de filter? Alles item types tonen lijkt me niet zo goed omdat we ook itemtypes, zoals 'partner, krijgen die daar niet in thuis horen


![image](https://user-images.githubusercontent.com/3798589/28532497-4222a55c-709a-11e7-96c0-1c9fb20c3ca5.png)

![image](https://user-images.githubusercontent.com/3798589/28532506-49d40aca-709a-11e7-97a7-c7fe0f3ac3c2.png)

![image](https://user-images.githubusercontent.com/3798589/28532585-83719676-709a-11e7-8a06-7002c5124170.png)

**Comment by JorisLambrechts** [comment]
Europeana en dergelijke zetten we idd best in Source, dan kan er nog steeds op gefilterd worden.

Voor het tweede punt: Intussen heb ik ingesteld dat je ook een 'Object' kan contributen, ik zal het item type 'Contributed' dan verwijderen. (het is gewoon een instelling van de plugin).

**Comment by roxannewyns** [comment]
@naeemmuhammad 
Al imported items should get as item type 'Object'
The information that currently goes to type (WITHin, Europeana...) should go to the dc:source metadata field instead if possible. This because we can't filter on multiple types using the solr facet browse. 

![image](https://user-images.githubusercontent.com/3798589/28874161-e32fb410-7790-11e7-8cca-cdb1145b5307.png)

**Comment by naeemmuhammad** [comment]
In fix 27799284d664e03d4e1f48503d1ea2b92275cf3f Item type has been set to Object for all imported items.

In fix 4766054d7c4e1b11b4a8efee266690dd48e3f2b4 search source is added to dc:source field.
