### ISSUE TITLE
Guest user

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#11]
I just registered myself as a guest user. I don't appear in the overview of guest user (also not after activation of the account). I do appear in the user overview.

![image](https://user-images.githubusercontent.com/3798589/28531812-2d9aa2d0-7098-11e7-8e95-597e9fb8fd5d.png)

![image](https://user-images.githubusercontent.com/3798589/28531792-223b7fcc-7098-11e7-93ba-4129901cbe30.png)

**Comment by naeemmuhammad** [comment]
User account moderation will be done via Gebruikers link in top navigation bar. 
Guest users link from left navigation menu will be hidden.
