### ISSUE TITLE
guest user can change contributed items publication status

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#13]
I'm logged in as a guest user and I can change the publication status.
Standard publication status should be "Needs review" and not "Public"

![image](https://user-images.githubusercontent.com/3798589/28532397-f0c00038-7099-11e7-8fb2-f9b2c96ada26.png)

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/Aezel-erfgoed-omeka/commit/1726a7eaace6e8ecbdf51ff2cd5eb84692d32500
