### ISSUE TITLE
filter option for own items, exhibits, collections is missing

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#15]
Add filter option like in Europeana Space so users see their own items by default but have the possibility to show all items if they want by clicking on a filter

![image](https://user-images.githubusercontent.com/3798589/28533108-3be510d8-709c-11e7-9af0-8e253b5456b5.png)

**Comment by naeemmuhammad** [comment]
Fixes:
https://github.com/libis/Aezel-erfgoed-omeka/commit/2605843255f9c8564ac2e3677b4aa09bff579cd7
https://github.com/libis/Aezel-erfgoed-omeka/commit/211f27011e3d9dc8dc23b5b8d3264d2564cbea6a
https://github.com/libis/Aezel-erfgoed-omeka/commit/48145f376d28c2481d77527257e1182d00cceb0c
