### ISSUE TITLE
wrong user role assigned when registering

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#16]
it seems to me that a wrong user role is assigned when registering; A normal  guest user should not be able to use the image manager, change contributed item publication statussed, make changes to the solr search...

**Comment by naeemmuhammad** [comment]
Following plugins are now hidden from the contributor user:
GuestUser, UserProfiles, Contribution, SolrSearch, ImageManager.

Also 'Item types' link from admin navigation menu is hidden for contributor user.
