### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#17]
'Bekijk eigen collecties' instead of 'View own collections'

![image](https://user-images.githubusercontent.com/3798589/28785998-3345a2fe-7618-11e7-8474-e423fd3c9e64.png)

'Eigen items' instead of 'Own'
![image](https://user-images.githubusercontent.com/3798589/28786073-62595bc6-7618-11e7-9704-718c6f1983b4.png)

'Bekijk eigen tentoonstellingen' instead of 'View own exhibit'
'Bekijk alle tentoonstellingen' instead of 'View all exhibit'
![image](https://user-images.githubusercontent.com/3798589/28786125-8c6afd8e-7618-11e7-86e0-14851c3ba27f.png)

**Comment by naeemmuhammad** [comment]
Fixes:
48c6921040ae2c666574894fa50eac7e87c9e74a
5143301947318ec0108524bd0bd95e3d47e34755
4665875792d26f0999a0ccb1d3256617dfe4b9ee
c2a1851b9d51974fdd700651d7d31d8ba51e0223
