### ISSUE TITLE
imported items have no images

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#20]
![image](https://user-images.githubusercontent.com/3798589/28874486-51585f04-7792-11e7-9489-3da18ce898f1.png)

**Comment by roxannewyns** [comment]
Images no longer appear after importing; This appears to be the case even when Europeana still provides one. Can you check

**Comment by roxannewyns** [comment]
for example a search on 'Koffie' (europeana only)
![image](https://user-images.githubusercontent.com/3798589/30061686-97127e5a-9248-11e7-8572-60b40df94e38.png)

![image](https://user-images.githubusercontent.com/3798589/30061763-f9008f12-9248-11e7-926b-172674c6f8b0.png)

**Comment by naeemmuhammad** [comment]
Images are not being downloaded on aezel server because of access restrictions. I have asked ICTS to provide necessary access to external urls so that images are downloaded and shown in omeka.

**Comment by naeemmuhammad** [comment]
Issue is solved. ICTS has provided necessary access to fetch images from external urls.
