### ISSUE TITLE
Remove add to collection function from Europeana search plugin

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#25]
Please remove the option to add online items to a collection. Collections will not be used in Aezel because it is not possible to filter on multiple collections or add the same object to more then 1 collection.

Please investigate the possibility to add tags instead. The tag field should also give a pop-up if a tag already exists (all tags can show up, not just the one created by the user). Don't implement it right away, but let me know how much work would this be? 

![image](https://user-images.githubusercontent.com/3798589/28880322-fa5dbb1e-77a4-11e7-94da-c8e328050e54.png)

**Comment by naeemmuhammad** [comment]
Import items to collection option has been removed from the interface: ee0f2c43ae5c28cb96c64068c498bc9ac4d514c9. Users will have no option to select a collection or provide name for a new collection. However, the underline functionality of adding items to a collection still remains part of the plugin.
