### ISSUE TITLE
Logo - kleine aanpassing

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#28]
LGGI aanpassen in Aezel. Hoofdletter en kleine letters ipv all caps. Niet in Italic

![image](https://user-images.githubusercontent.com/3798589/30061194-ba875b00-9246-11e7-873a-437679571a36.png)

**Comment by roxannewyns** [comment]
Sorry, een detail, maar ze wilden Aezel i.p.v. AEZEL.

**Comment by JorisLambrechts** [comment]
Is ok, zat nog in de cache om de een of andere reden
