### ISSUE TITLE
Zoek online (/libco/search) - Change order of database list

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#29]
![image](https://user-images.githubusercontent.com/3798589/30061854-522676d8-9249-11e7-8588-9df00fcffba9.png)

The partner would like to see it in the following order
•	Europeana 
•	Rijksmuseum
•	Historypin
•	WITHin
•	DPLA
•	DDB
•	InternetArchive
•	Brittish Library
•	DigitalNZ
•	EuropeanaFashion
•	NLA

**Comment by naeemmuhammad** [comment]
List of sources is retrieved from the WITH api repository, therefore the list can change (grow or shrink) based on changes in the repository. However, there is a possibility to manipulate the source list after receiving it from the WITH api repository. The received list can be reorder, however if a source is missing in the received list, it will be not be displayed. About a day of work can be foreseen for this.

**Comment by roxannewyns** [comment]
geen antwoord meer van partner. voorlopig geen wijzigingen doorvoeren.
