### ISSUE TITLE
Registratie mail naar site beheerder

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#34]
Een gebruiker kan zich registreren (/aezel-erfgoed/guest-user/user/register). Na registratie wordt een email gezonden naar de site beheerder die de account dan moet activeren. Naar welk email adres wordt dit nu gezonden? Kan ik dit zelf aanpassen en waar, of moet dit in de code?

**Comment by JorisLambrechts** [comment]
Dat gaat gewoon naar de site beheerder. Dat staat nog op mijn naam, maar kan aangepast worden op: /admin/settings/edit-settings (de algemene settings dus)

**Comment by roxannewyns** [comment]
Ok, dat was wat ik moest weten. Ik pas het wel aan.
