### ISSUE TITLE
recaptcha activeren

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#35]
Registratiepagina heeft geen recaptcha. Gelieve dit toe te voegen. Je kan de gegevens erugvinden op de l schijf onderDocumenten\Serverdocumenten\Rode Map\Heron in het document Heron_paswoorden.docx op pagina 7.

![image](https://user-images.githubusercontent.com/3798589/30063841-3e3e6a3e-9250-11e7-81a0-09e9db05d029.png)

**Comment by roxannewyns** [comment]
Ook op LGGI site toevoegen.

**Comment by JorisLambrechts** [comment]
in orde
