### ISSUE TITLE
partner pagina 

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#9]
Misschien heb je dit niet gedeployed? 

Er is een simple page met titel 'Partner x' en slug 'partner-x'.

    Er is een item 'Partner x' verbonden met de simple page via tag 'partner-x' (moet gelijk zijn aan de slug van de page)
        In de resultatenlijst linkt dit item naar de simple page ipv een item (voorlopig via metadata-veld 'page'), de item-show pagina van dit item wordt best nooit getoond
        De eerste afbeelding van dit item is het logo (zoals in de mockup)
        De volgende afbeelding wordt volledig getoond (de grote foto op de mockup)
    Er is een collectie 'Partner x', deze heeft dezelfde titel als de pagina aangezien een collectie geen tags kan hebben (het Partner-item zit niet in de collectie)
    Er zijn tentoonstellingen van Partner x die via tag 'partner-x' te vinden zijn
    Onderliggende paginas zijn gewoon verbonden via onderlinge relaties van de simple page plugin

Hierbij een simple page met als slug de-domeinen
En items met als tag De Domeinen

![image](https://user-images.githubusercontent.com/3798589/28530254-877b0100-7093-11e7-82b5-5d0703290ed3.png)
![image](https://user-images.githubusercontent.com/3798589/28530263-8e475448-7093-11e7-9cc2-09e857255bd4.png)

**Comment by roxannewyns** [comment]
Alle partners op home page moet linken naar /aezel-erfgoed/solr-search?q=&facet=itemtype:%22Partner%22

![image](https://user-images.githubusercontent.com/3798589/28530307-ba63456e-7093-11e7-814b-75801e76a9fd.png)

**Comment by roxannewyns** [comment]
Aanklikken van het partner icoon op de home page moet rechtsreeks naar partner simple page verwijzen.
![image](https://user-images.githubusercontent.com/3798589/28530345-d6223d82-7093-11e7-85f7-3f9977c6bd1d.png)

**Comment by roxannewyns** [comment]
partner result page moet rechtstreeks doorlinken naar partner simple page i.p.v. naar item detail page te gaan
![image](https://user-images.githubusercontent.com/3798589/28530499-57511e50-7094-11e7-93bc-89b0409613c7.png)

**Comment by roxannewyns** [comment]
Werkt nog niet. Geen link op home page. Enkel link naar alle projecten. Bij alle projecten (browse page) geeft aanklikken van een item nog steeds de item show page ipv de bijhorende simple page.

**Comment by JorisLambrechts** [comment]
Ik ging er van uit dat het metadataveld 'page' ingevuld moest worden. Gewoon de slug van de simple page moet er komen.

Of moet ik de titel automatisch omzetten naar de slug van de pagina? Dan moeten ze 'page' niet zelf invullen maar dan kunnen er wel dode links opduiken als ze hun simple pages niet consequent aanmaken

**Comment by roxannewyns** [comment]
Had niet door hoe het werkte. Is ok zo.
